### ISSUE TITLE
swalfire error

### ISSUE THREAD

**Issue by IT21298912** [moshdev2213/ICare-Medicals#32]
<script>
import axios from 'axios';
import Swal from 'sweetalert2'
const Swal = require('sweetalert2')

export default {
  data() {
    return {
      doctor: {
        email: '',
        firstName: '',
        lastName: '',
        timeAvailabe: '',
        description: '',
        specializing: '',
        status: '',
        amount: '',
        cured: '',
        venue: '',
        added: '',
        edited: ''
      },
      isValidEmail: true,
      isValidFirstName: true,
      isValidLastName: true,
      isValidTimeAvailable: true,
      isValidDescription: true,
      isValidSpecialization: true,
      isValidStatus: true,
      isValidAmount: true,
      isValidCured: true,
      isValidVenue: true,
      isValidAdded: true,
      isValidEdited: true,
      isFormValid: true
    };
  },
  methods: {
    submitForm() {

      Swal.fire('SweetAlert2 is working!')
      this.validateForm();

      if (this.isFormValid) {

        // Send a POST request to your Spring Boot API
        axios
          .post('http://localhost:8083/api/v1/doctor/save', this.doctor)
          .then((response) => {
            console.log('Doctor data sent successfully:', response.data);

            // Optionally, you can reset the form fields here
            this.doctor.email = '';
            this.doctor.firstName = '';
            this.doctor.lastName = '';
            this.doctor.timeAvailabe = '';
            this.doctor.description = '';
            this.doctor.specializing = '';
            this.doctor.status = '';
            this.doctor.amount = '';
            this.doctor.cured = '';
            this.doctor.venue = '';
            this.doctor.added = '';
            this.doctor.edited = '';

           
          })
          .catch((error) => {
            console.error('Error sending doctor data:', error);
          });
      }
    },
    validateForm() {
      this.isValidEmail = this.isValidEmailFormat(this.doctor.email);
      this.isValidFirstName = this.isValidField(this.doctor.firstName);
      this.isValidLastName = this.isValidField(this.doctor.lastName);
      this.isValidTimeAvailable = this.isValidField(this.doctor.timeAvailabe);
      this.isValidDescription = this.isValidField(this.doctor.description);
      this.isValidSpecialization = this.isValidField(this.doctor.specializing);
     // this.isValidStatus = this.isValidField(this.doctor.status);
     // this.isValidAmount = this.isValidField(this.doctor.amount);
     // this.isValidCured = this.isValidField(this.doctor.cured);
      this.isValidVenue = this.isValidField(this.doctor.venue);
      this.isValidAdded = this.isValidField(this.doctor.added);
      this.isValidEdited = this.isValidField(this.doctor.edited);

      this.isFormValid =
        this.isValidEmail &&
        this.isValidFirstName &&
        this.isValidLastName &&
        this.isValidTimeAvailable &&
        this.isValidDescription &&
        this.isValidSpecialization &&
        this.isValidStatus &&
        this.isValidAmount &&
        this.isValidCured &&
        this.isValidVenue &&
        this.isValidAdded &&
        this.isValidEdited;
    },
    isValidEmailFormat(email) {
      // Add your email validation logic here (e.g., regex)
      // Return true if valid, false otherwise
       return /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/.test(email);
    },
    isValidField(value) {
      return typeof value === 'string' && value.trim() !== '';
    }
  }
};
</script>

          why sweet alert not pop up

**Comment by moshdev2213** [comment]
the related npm package was not installed correctly , install it in the main.js globally
